# Generated by Django 4.2.7 on 2023-12-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseordermodel',
            old_name='po_number',
            new_name='po_id',
        ),
    ]
