# Generated by Django 4.2.7 on 2023-12-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_purchaseordermodel_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=255),
        ),
    ]
