# Generated by Django 4.2.7 on 2023-12-04 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_purchaseordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicperformancemodel',
            name='total_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 17, 9, 34, 757427, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicperformancemodel',
            name='average_response_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historicperformancemodel',
            name='fulfillment_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historicperformancemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicperformancemodel',
            name='on_time_delivery_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historicperformancemodel',
            name='quality_rating_avg',
            field=models.FloatField(default=0),
        ),
    ]
