# Generated by Django 4.2.7 on 2023-12-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_historicperformancemodel_total_deliveries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicperformancemodel',
            name='average_response_time',
            field=models.IntegerField(default=0),
        ),
    ]
