# Generated by Django 4.2.7 on 2023-12-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_historicperformancemodel_average_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicperformancemodel',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
